#!/usr/bin/env python
import sys
import json
from reporter.reporter import totals_str


def run():
    prog_name = sys.argv[0]
    if len(sys.argv) != 2:
        print('Usage: {} info_file_path'.format(prog_name))
        sys.exit(1)

    info_file_path = sys.argv[1]

    with open(info_file_path,'r') as data_file:
        info = json.load(data_file)

    print(totals_str(info))

if __name__ == '__main__':
    run()



